[package]
name = "pkger"
version = "0.1.0"
authors = ["wojciech.kepka <wojtek.kepka@protonmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/wojciechkepka/pkger"
repository = "https://github.com/wojciechkepka/pkger"
keywords = ["unix", "linux", "deb", "rpm", "build"]
description = "Building tool inspired by fpm-builder"
categories = ["command-line-utilities"]


[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
tar = "0.4"
structopt = "0.3.21"
clap = "2"
bytes = "1"
git2 = "0.13.0"
futures = "0.3"
byteorder = "1.4"
tracing = "0.1"
tracing-futures = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "chrono"] }
moby = { git = "https://github.com/wojciechkepka/moby", branch = "master" }
rpmspec = { git = "https://github.com/wojciechkepka/rpmspec-rs", branch = "master" }
