[package]
name = "pkger"
version = "0.1.0"
authors = ["wojciech.kepka <wojtek.kepka@protonmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/wojciechkepka/pkger"
repository = "https://github.com/wojciechkepka/pkger"
keywords = ["unix", "linux", "deb", "rpm", "build"]
description = "Building tool inspired by fpm-builder"
categories = ["command-line-utilities"]


[[bin]]
name = "pkger"
path = "src/main.rs"

[lib]
name = "pkger"

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
tar = "0.4"
structopt = "0.3.21"
clap = "2"
rpm-rs = "0.6"
bytes = "1"
git2 = "0.13.0"
futures = "0.3"
byteorder = "1.4"
tracing-subscriber = "0.2"
moby = { git = "https://github.com/wojciechkepka/moby", branch = "master" }
