[package]
name = "pkger-core"
version = "0.4.0"
edition = "2018"
authors = ["wojciech.kepka <wojciech@wkepka.dev>"]
license = "MIT"

[dependencies]
deb-control = { path = "../libs/debcontrol" }
rpmspec = { path = "../libs/rpmspec" }
pkgbuild = { path = "../libs/pkgbuild" }

docker-api = "0.4"

anyhow = "1"

tar = "0.4"
flate2 = "1"

tracing = "0.1"

futures = "0.3"

serde = {version = "1.0", features = ["derive"]}
serde_cbor = "0.11"
serde_yaml = "0.8"

tempdir = "0.3"

[dev-dependencies]
pretty_assertions = "0.3"
