[metadata]
name = "pkger"
description = "pkger"
arch = "x86_64"
license = "MIT"
version = "0.0.5"
revision = "0"
source = ""
git = "https://github.com/wojciechkepka/pkger.git"
build_depends = ["curl", "gcc", "pkg-config", "centos8{openssl-devel},debian10{libssl-dev}"]
exclude = ["share", "info"]
provides = ["pkger"]
images = [
	{ name = "centos8", target = "rpm" },
    { name = "debian10", target = "deb" }
]

[build]
steps = [
	"curl -o /tmp/install_rust.sh https://sh.rustup.rs",
	"sh /tmp/install_rust.sh -y --default-toolchain stable",
	"mkdir -p /opt/pkger/bin",
	"/root/.cargo/bin/cargo build --target-dir $PKGER_BLD_DIR",
]
